// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountSecurity struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
	DeviceID  int64
}

type BlockedUser struct {
	ID        pgtype.Int8
	BlockerID int64
	BlockedID int64
	CreatedAt pgtype.Timestamp
}

type Chat struct {
	ChatID         int64
	UserID         int64
	FriendID       int64
	UnreadMessages pgtype.Int8
	LastMessageAt  pgtype.Timestamptz
	Viewed         pgtype.Bool
	ViewedAt       pgtype.Timestamptz
}

type Friend struct {
	ID        int64
	UserID    int64
	FriendID  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MutedUser struct {
	ChatID    int64
	MuterID   int64
	MutedID   int64
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type Privacy struct {
	UserID       int64
	IsPrivate    pgtype.Bool
	IsSearchable pgtype.Bool
}

type Session struct {
	ID        int64
	UserID    int64
	DeviceID  string
	DeviceOs  string
	IpAddress string
}

type User struct {
	ID        int64
	Username  string
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarID  pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
