// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendList struct {
	ID        int64
	UserID    int64
	FriendID  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Privacy struct {
	UserID       int64
	IsPrivate    pgtype.Bool
	IsSearchable pgtype.Bool
}

type Session struct {
	ID        int64
	UserID    int64
	DeviceID  string
	DeviceOs  string
	IpAddress string
}

type User struct {
	ID        int64
	Username  string
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarID  pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserSecurity struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
	DeviceID  int64
}
