DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS privacy;
DROP TABLE IF EXISTS account_security;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS friend;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS muted_users;
DROP TABLE IF EXISTS blocked_users;
